import type { SearchAdReportType } from "./types";

export const ALL_SEARCH_AD_REPORT_TYPES: SearchAdReportType[] = [
  "AD",
  "AD_DETAIL",
  "AD_CONVERSION",
  "AD_CONVERSION_DETAIL",
  "ADEXTENSION",
  "EXPKEYWORD",
  "SHOPPINGKEYWORD_DETAIL",
  "SHOPPINGKEYWORD_CONVERSION_DETAIL",
  "CRITERION",
  "CRITERION_CONVERSION",
];

export const DEFAULT_SEARCH_AD_BACKFILL_REPORT_TYPES: SearchAdReportType[] = ALL_SEARCH_AD_REPORT_TYPES;

export const SEARCH_AD_REPORT_RETENTION_DAYS: Record<SearchAdReportType, number> = {
  AD: 365,
  AD_CONVERSION: 365,
  AD_CONVERSION_DETAIL: 45,
  AD_DETAIL: 180,
  ADEXTENSION: 365,
  CRITERION: 365,
  CRITERION_CONVERSION: 365,
  EXPKEYWORD: 365,
  SHOPPINGKEYWORD_CONVERSION_DETAIL: 45,
  SHOPPINGKEYWORD_DETAIL: 180,
};

export const SEARCH_AD_MAX_REPORT_RETENTION_DAYS = Math.max(...Object.values(SEARCH_AD_REPORT_RETENTION_DAYS));
