import type { SearchAdReportType } from "./types";

export type SearchAdReportColumn = {
  key: string;
  label: string;
  description: string;
  numeric?: boolean;
};

export const SEARCH_AD_REPORT_PARSER_VERSION = "search-ad-report-parser-v1";

export const REPORT_COLUMN_SCHEMAS: Record<SearchAdReportType, SearchAdReportColumn[]> = {
  AD: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "campaignId", label: "캠페인 ID", description: "네이버 캠페인 식별자" },
    { key: "adgroupId", label: "광고그룹 ID", description: "네이버 광고그룹 식별자" },
    { key: "keywordId", label: "키워드 ID", description: "파워링크 키워드 식별자. 쇼핑검색광고는 '-'일 수 있습니다." },
    { key: "adId", label: "광고 ID", description: "네이버 광고 소재 식별자" },
    { key: "businessChannelId", label: "비즈채널 ID", description: "연결된 비즈채널 식별자" },
    { key: "mediaId", label: "매체 ID", description: "광고가 노출된 매체 식별자" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "impressions", label: "노출수", description: "광고가 노출된 횟수", numeric: true },
    { key: "clicks", label: "클릭수", description: "광고 클릭 횟수", numeric: true },
    { key: "cost", label: "비용", description: "광고비 합계", numeric: true },
    { key: "averagePosition", label: "평균 노출 순위", description: "평균 노출 위치", numeric: true },
    { key: "status", label: "상태", description: "보고서 기준 대상 상태" },
  ],
  AD_DETAIL: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "campaignId", label: "캠페인 ID", description: "네이버 캠페인 식별자" },
    { key: "adgroupId", label: "광고그룹 ID", description: "네이버 광고그룹 식별자" },
    { key: "keywordId", label: "키워드 ID", description: "파워링크 키워드 식별자. 쇼핑검색광고는 '-'일 수 있습니다." },
    { key: "adId", label: "광고 ID", description: "네이버 광고 소재 식별자" },
    { key: "businessChannelId", label: "비즈채널 ID", description: "연결된 비즈채널 식별자" },
    { key: "detailGroup", label: "세부 구분", description: "보고서 세부 분류 코드" },
    { key: "detailCode", label: "세부 코드", description: "보고서 세부 코드" },
    { key: "mediaId", label: "매체 ID", description: "광고가 노출된 매체 식별자" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "impressions", label: "노출수", description: "광고가 노출된 횟수", numeric: true },
    { key: "clicks", label: "클릭수", description: "광고 클릭 횟수", numeric: true },
    { key: "cost", label: "비용", description: "광고비 합계", numeric: true },
    { key: "averagePosition", label: "평균 노출 순위", description: "평균 노출 위치", numeric: true },
    { key: "status", label: "상태", description: "보고서 기준 대상 상태" },
  ],
  AD_CONVERSION: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "campaignId", label: "캠페인 ID", description: "네이버 캠페인 식별자" },
    { key: "adgroupId", label: "광고그룹 ID", description: "네이버 광고그룹 식별자" },
    { key: "keywordId", label: "키워드 ID", description: "파워링크 키워드 식별자. 쇼핑검색광고는 '-'일 수 있습니다." },
    { key: "adId", label: "광고 ID", description: "네이버 광고 소재 식별자" },
    { key: "businessChannelId", label: "비즈채널 ID", description: "연결된 비즈채널 식별자" },
    { key: "mediaId", label: "매체 ID", description: "광고가 노출된 매체 식별자" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "conversionMethod", label: "전환 방식", description: "직접/간접 전환 구분" },
    { key: "conversionType", label: "전환 유형", description: "구매, 장바구니 등 전환 분류" },
    { key: "conversions", label: "전환수", description: "전환 수", numeric: true },
    { key: "salesAmount", label: "전환매출", description: "전환 매출", numeric: true },
  ],
  AD_CONVERSION_DETAIL: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "campaignId", label: "캠페인 ID", description: "네이버 캠페인 식별자" },
    { key: "adgroupId", label: "광고그룹 ID", description: "네이버 광고그룹 식별자" },
    { key: "keywordId", label: "키워드 ID", description: "파워링크 키워드 식별자. 쇼핑검색광고는 '-'일 수 있습니다." },
    { key: "adId", label: "광고 ID", description: "네이버 광고 소재 식별자" },
    { key: "businessChannelId", label: "비즈채널 ID", description: "연결된 비즈채널 식별자" },
    { key: "detailGroup", label: "세부 구분", description: "보고서 세부 분류 코드" },
    { key: "detailCode", label: "세부 코드", description: "보고서 세부 코드" },
    { key: "mediaId", label: "매체 ID", description: "광고가 노출된 매체 식별자" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "conversionMethod", label: "전환 방식", description: "직접/간접 전환 구분" },
    { key: "conversionType", label: "전환 유형", description: "구매, 장바구니 등 전환 분류" },
    { key: "conversions", label: "전환수", description: "전환 수", numeric: true },
    { key: "salesAmount", label: "전환매출", description: "전환 매출", numeric: true },
  ],
  ADEXTENSION: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "campaignId", label: "캠페인 ID", description: "네이버 캠페인 식별자" },
    { key: "adgroupId", label: "광고그룹 ID", description: "네이버 광고그룹 식별자" },
    { key: "keywordId", label: "키워드 ID", description: "파워링크 키워드 식별자. 쇼핑검색광고는 '-'일 수 있습니다." },
    { key: "adId", label: "광고 ID", description: "네이버 광고 소재 식별자" },
    { key: "extensionId", label: "확장소재 ID", description: "확장소재 식별자" },
    { key: "businessChannelId", label: "비즈채널 ID", description: "연결된 비즈채널 식별자" },
    { key: "mediaId", label: "매체 ID", description: "광고가 노출된 매체 식별자" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "impressions", label: "노출수", description: "광고가 노출된 횟수", numeric: true },
    { key: "clicks", label: "클릭수", description: "광고 클릭 횟수", numeric: true },
    { key: "cost", label: "비용", description: "광고비 합계", numeric: true },
    { key: "averagePosition", label: "평균 노출 순위", description: "평균 노출 위치", numeric: true },
    { key: "status", label: "상태", description: "확장소재 상태" },
  ],
  EXPKEYWORD: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "campaignId", label: "캠페인 ID", description: "네이버 캠페인 식별자" },
    { key: "adgroupId", label: "광고그룹 ID", description: "네이버 광고그룹 식별자" },
    { key: "searchTerm", label: "검색어", description: "실제 유입 또는 확장된 검색어" },
    { key: "mediaId", label: "매체 ID", description: "광고가 노출된 매체 식별자" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "clicks", label: "클릭수", description: "검색어 기준 클릭 수", numeric: true },
    { key: "averagePosition", label: "평균 노출 순위", description: "평균 노출 위치", numeric: true },
    { key: "cost", label: "비용", description: "검색어 기준 광고비", numeric: true },
    { key: "conversions", label: "전환수", description: "보고서에서 제공되는 경우의 전환 수", numeric: true },
    { key: "salesAmount", label: "전환매출", description: "보고서에서 제공되는 경우의 전환 매출", numeric: true },
  ],
  SHOPPINGKEYWORD_DETAIL: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "campaignId", label: "캠페인 ID", description: "쇼핑검색광고 캠페인 식별자" },
    { key: "adgroupId", label: "광고그룹 ID", description: "쇼핑검색광고 광고그룹 식별자" },
    { key: "searchTerm", label: "검색어", description: "실제 유입된 쇼핑검색 검색어" },
    { key: "adId", label: "광고 ID", description: "네이버 쇼핑검색광고 식별자" },
    { key: "businessChannelId", label: "비즈채널 ID", description: "연결된 비즈채널 식별자" },
    { key: "detailGroup", label: "세부 구분", description: "보고서 세부 분류 코드" },
    { key: "detailCode", label: "세부 코드", description: "보고서 세부 코드" },
    { key: "mediaId", label: "매체 ID", description: "광고가 노출된 매체 식별자" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "impressions", label: "노출수", description: "검색어 기준 노출 수", numeric: true },
    { key: "clicks", label: "클릭수", description: "검색어 기준 클릭 수", numeric: true },
    { key: "cost", label: "비용", description: "검색어 기준 광고비", numeric: true },
    { key: "averagePosition", label: "평균 노출 순위", description: "평균 노출 위치", numeric: true },
    { key: "status", label: "상태", description: "보고서 기준 상태" },
  ],
  SHOPPINGKEYWORD_CONVERSION_DETAIL: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "campaignId", label: "캠페인 ID", description: "쇼핑검색광고 캠페인 식별자" },
    { key: "adgroupId", label: "광고그룹 ID", description: "쇼핑검색광고 광고그룹 식별자" },
    { key: "searchTerm", label: "검색어", description: "전환이 연결된 쇼핑검색 검색어" },
    { key: "adId", label: "광고 ID", description: "네이버 쇼핑검색광고 식별자" },
    { key: "businessChannelId", label: "비즈채널 ID", description: "연결된 비즈채널 식별자" },
    { key: "detailGroup", label: "세부 구분", description: "보고서 세부 분류 코드" },
    { key: "detailCode", label: "세부 코드", description: "보고서 세부 코드" },
    { key: "mediaId", label: "매체 ID", description: "광고가 노출된 매체 식별자" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "conversionMethod", label: "전환 방식", description: "직접/간접 전환 구분" },
    { key: "conversionType", label: "전환 유형", description: "구매, 장바구니 등 전환 분류" },
    { key: "conversions", label: "전환수", description: "전환 수", numeric: true },
    { key: "salesAmount", label: "전환매출", description: "전환 매출", numeric: true },
  ],
  CRITERION: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "criterionId", label: "타게팅 ID", description: "광고그룹 ID와 타게팅 코드가 결합된 값" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "impressions", label: "노출수", description: "타게팅 기준 노출 수", numeric: true },
    { key: "clicks", label: "클릭수", description: "타게팅 기준 클릭 수", numeric: true },
    { key: "cost", label: "비용", description: "타게팅 기준 광고비", numeric: true },
  ],
  CRITERION_CONVERSION: [
    { key: "date", label: "기준일", description: "보고서 기준일" },
    { key: "customerId", label: "광고 계정 ID", description: "네이버 검색광고 고객 ID" },
    { key: "criterionId", label: "타게팅 ID", description: "광고그룹 ID와 타게팅 코드가 결합된 값" },
    { key: "device", label: "기기", description: "PC 또는 모바일 구분" },
    { key: "conversionMethod", label: "전환 방식", description: "직접/간접 전환 구분" },
    { key: "conversionType", label: "전환 유형", description: "구매, 장바구니 등 전환 분류" },
    { key: "conversions", label: "전환수", description: "타게팅 기준 전환 수", numeric: true },
    { key: "salesAmount", label: "전환매출", description: "타게팅 기준 전환 매출", numeric: true },
  ],
};

export function getReportColumns(reportType: SearchAdReportType) {
  return REPORT_COLUMN_SCHEMAS[reportType];
}
