import type { ProviderDataContractView } from "./types";

export function buildProviderDataContracts(): ProviderDataContractView[] {
  return [
    {
      providerKey: "search_ad",
      providerLabel: "네이버 키워드광고",
      channelKey: "search-ad",
      channelLabel: "마케팅 데이터",
      sourceUrl: "https://api.searchad.naver.com/keywordstool",
      incoming: {
        id: "search-ad-incoming",
        title: "불러오는 데이터",
        description:
          "키워드 도구 응답에서 후보 키워드 수요를 읽고, /stats 집계와 쇼핑검색광고 전용 검색어 성과를 함께 읽습니다.",
        safetyNote: "API 키, 서명, 고객 ID, 응답 원문은 저장하지 않습니다.",
        columns: [
          {
            key: "relKeyword",
            label: "키워드",
            description: "네이버 키워드 도구가 반환한 실제 연관 키워드입니다.",
            sample: "부처님오신날 선물카드",
          },
          {
            key: "monthlyPcQcCnt",
            label: "PC 월간 검색수",
            description: "PC에서 조회된 월간 검색량입니다. '< 10' 같은 값은 0으로 정규화합니다.",
            sample: "420",
          },
          {
            key: "monthlyMobileQcCnt",
            label: "모바일 월간 검색수",
            description: "모바일에서 조회된 월간 검색량입니다.",
            sample: "1,800",
          },
          {
            key: "compIdx",
            label: "경쟁도",
            description: "낮음, 중간, 높음 값을 LOW, MEDIUM, HIGH로 바꿉니다.",
            sample: "중간",
          },
          {
            key: "monthlyAvePcCtr",
            label: "PC 평균 클릭률",
            description: "PC 광고 평균 클릭률 후보 값입니다.",
            sample: "1.2",
          },
          {
            key: "monthlyAveMobileCtr",
            label: "모바일 평균 클릭률",
            description: "모바일 광고 평균 클릭률 후보 값입니다.",
            sample: "1.8",
          },
          {
            key: "GET /stats",
            label: "성과 집계",
            description: "키워드/광고그룹/캠페인 단위의 노출, 클릭, 비용, 전환, 매출 집계를 읽는 검색광고 통계 요청입니다.",
            sample: "fields=impCnt,clkCnt,salesAmt,ccnt,convAmt",
          },
          {
            key: "breakdown",
            label: "기기/시간대 구분",
            description: "PC/모바일, 요일, 시간대 같은 성과 분해 조건입니다. 공식 제공 범위 안에서만 판단합니다.",
            sample: "pcMblTp 또는 hh24",
          },
          {
            key: "statType=NPLA_SCH_KEYWORD",
            label: "쇼핑검색어 성과",
            description: "쇼핑검색광고 전용으로 최근 30일 검색어별 클릭, 직접 전환율, 광고비를 읽습니다.",
            sample: "schKeyword, clkCnt, drtCrto, salesAmt",
          },
        ],
        sampleRows: [
          {
            id: "search-ad-incoming-sample-1",
            values: [
              { key: "relKeyword", label: "키워드", value: "부처님오신날 선물카드" },
              { key: "monthlyPcQcCnt", label: "PC", value: "420" },
              { key: "monthlyMobileQcCnt", label: "모바일", value: "1,800" },
              { key: "compIdx", label: "경쟁도", value: "중간" },
              { key: "monthlyAvePcCtr", label: "PC CTR", value: "1.2" },
            ],
          },
        ],
        sourceFieldGroups: [
          {
            id: "search-ad-source-keyword-list",
            title: "keywordList[0]",
            description: "네이버 키워드 도구 응답의 원문 필드입니다. 클릭률/클릭수/경쟁도는 키워드 선별 때 추가 점검 후보로 봅니다.",
            fields: [
              { key: "keywordList", label: "키워드 목록", handling: "응답 루트 배열" },
              { key: "keywordList[0].relKeyword", label: "키워드", handling: "키워드 수요 요약에 사용" },
              { key: "keywordList[0].monthlyPcQcCnt", label: "PC 검색수", handling: "숫자로 정규화해 저장" },
              { key: "keywordList[0].monthlyMobileQcCnt", label: "모바일 검색수", handling: "숫자로 정규화해 저장" },
              { key: "keywordList[0].monthlyAvePcClkCnt", label: "PC 평균 클릭수", handling: "선택 전 확인, 기본 저장 안 함" },
              { key: "keywordList[0].monthlyAveMobileClkCnt", label: "모바일 평균 클릭수", handling: "선택 전 확인, 기본 저장 안 함" },
              { key: "keywordList[0].monthlyAvePcCtr", label: "PC 클릭률", handling: "클릭률 후보로 저장" },
              { key: "keywordList[0].monthlyAveMobileCtr", label: "모바일 클릭률", handling: "클릭률 후보로 저장" },
              { key: "keywordList[0].plAvgDepth", label: "평균 노출 순위", handling: "선택 전 확인, 기본 저장 안 함" },
              { key: "keywordList[0].compIdx", label: "경쟁도", handling: "경쟁 수준으로 변환" },
            ],
          },
          {
            id: "search-ad-source-discovery",
            title: "성과 대상 자동 발견",
            description: "성과 조회 대상 ID가 따로 설정되지 않았을 때 캠페인, 광고그룹, 키워드를 읽기 전용으로 찾는 원천 필드입니다.",
            fields: [
              { key: "GET /ncc/campaigns[].nccCampaignId", label: "캠페인 ID", handling: "광고그룹 조회와 캠페인명 연결에 사용" },
              { key: "GET /ncc/campaigns[].name", label: "캠페인명", handling: "브랜드 추정과 화면 표시명에 사용" },
              { key: "GET /ncc/campaigns[].status", label: "캠페인 상태", handling: "켜진 키워드 여부 계산에 사용" },
              { key: "GET /ncc/campaigns[].userLock", label: "캠페인 잠금", handling: "잠긴 캠페인은 꺼진 키워드로 계산" },
              { key: "GET /ncc/campaigns[].campaignTp", label: "캠페인 유형", handling: "파워링크/쇼핑검색광고 분리 기준으로 사용" },
              { key: "GET /ncc/campaigns[].trackingMode", label: "전환 추적 설정", handling: "추적 확인 여부 기본값에 사용" },
              { key: "GET /ncc/adgroups[].nccAdgroupId", label: "광고그룹 ID", handling: "키워드 조회와 광고그룹명 연결에 사용" },
              { key: "GET /ncc/adgroups[].name", label: "광고그룹명", handling: "브랜드 추정과 화면 표시명에 사용" },
              { key: "GET /ncc/adgroups[].status", label: "광고그룹 상태", handling: "켜진 키워드 여부 계산에 사용" },
              { key: "GET /ncc/adgroups[].userLock", label: "광고그룹 잠금", handling: "잠긴 광고그룹은 꺼진 키워드로 계산" },
              { key: "GET /ncc/adgroups[].adgroupType", label: "광고그룹 유형", handling: "SHOPPING, CATALOG, SHOPPING_BRAND이면 쇼핑검색광고 성과 후보로 사용" },
              { key: "GET /ncc/adgroups[].nccProductGroupId", label: "상품 그룹 ID", handling: "쇼핑검색광고 상품 그룹/몰 연결에 사용" },
              { key: "GET /ncc/keywords[].nccKeywordId", label: "광고 키워드 ID", handling: "/stats 조회 대상 ID로 사용" },
              { key: "GET /ncc/keywords[].keyword", label: "광고 키워드명", handling: "성과 스냅샷 키워드명으로 저장" },
              { key: "GET /ncc/keywords[].status", label: "키워드 상태", handling: "전체 키워드 목록과 켜진 키워드 요약에 저장" },
              { key: "GET /ncc/keywords[].userLock", label: "키워드 잠금", handling: "잠긴 키워드는 꺼진 키워드로 계산" },
              { key: "GET /ncc/product-groups[].mallName", label: "쇼핑몰명", handling: "쇼핑검색광고 성과의 몰/브랜드 근거로 저장" },
              { key: "GET /ncc/product-groups[].attrJson", label: "상품 그룹 속성", handling: "이미지 URL 후보가 있으면 대표 이미지로 저장, 없으면 대체 썸네일 사용" },
              { key: "GET /ncc/product-groups[].registeredProductType", label: "상품 등록 유형", handling: "일반형/카탈로그형 구분 근거로 저장" },
            ],
          },
          {
            id: "search-ad-source-stats",
            title: "GET /stats 성과 집계",
            description: "네이버 검색광고 통계 API의 원문 요청/응답 후보입니다. LLM 전 규칙 엔진이 먼저 낮은 전환율, 주문 없는 클릭, 높은 CPA, 기기/시간대 차이를 계산합니다.",
            fields: [
              { key: "id 또는 ids", label: "조회 대상 ID", handling: "캠페인/광고그룹/키워드 단위 집계 대상" },
              { key: "fields", label: "지표 목록", handling: "impCnt, clkCnt, salesAmt, ccnt, convAmt, ctr, crto, ror, cpConv 후보" },
              { key: "timeRange", label: "조회 기간", handling: "최근 7일/30일 같은 집계 기간으로 저장" },
              { key: "timeIncrement", label: "집계 단위", handling: "일별 추이 필요 시 점검" },
              { key: "breakdown=pcMblTp", label: "PC/모바일", handling: "기기 성과 차이 규칙에 사용" },
              { key: "breakdown=hh24", label: "시간대", handling: "시간대 성과 차이 규칙에 사용" },
              { key: "breakdown=dayw", label: "요일", handling: "요일 성과 차이 후보, 기본 안건은 보수 처리" },
              { key: "summaryStatResponse.data[0].impCnt", label: "노출수", handling: "성과 스냅샷 노출수로 저장" },
              { key: "summaryStatResponse.data[0].clkCnt", label: "클릭수", handling: "주문 없는 클릭/표본 기준에 사용" },
              { key: "summaryStatResponse.data[0].salesAmt", label: "광고비", handling: "CPA/예산 낭비 규칙에 사용" },
              { key: "summaryStatResponse.data[0].ccnt", label: "전환수", handling: "전환율과 주문 없음 규칙에 사용" },
              { key: "summaryStatResponse.data[0].convAmt", label: "전환매출", handling: "ROAS 후보로 저장" },
              { key: "summaryStatResponse.data[0].breakdowns[]", label: "분해 성과", handling: "PC/모바일 또는 시간대별 스냅샷으로 펼쳐 저장" },
              { key: "GET /stats?id={adgroupId}&statType=NPLA_SCH_KEYWORD", label: "쇼핑검색어 성과", handling: "쇼핑검색광고 검색어별 클릭/직접전환율/광고비 스냅샷으로 저장" },
              { key: "NPLA_SCH_KEYWORD[].schKeyword", label: "쇼핑 검색어", handling: "상품 노출 검색어 판단에 사용" },
              { key: "NPLA_SCH_KEYWORD[].drtCrto", label: "직접 전환율", handling: "직접전환 없음/낮은 전환율 규칙에 사용" },
            ],
          },
        ],
      },
      stored: {
        id: "search-ad-stored",
        title: "저장하는 데이터",
        description: "원천 응답을 그대로 두지 않고 키워드 수요 요약, 성과 집계 스냅샷, 연동 실행 기록으로 저장합니다.",
        safetyNote: "AI 입력에는 키워드와 요약 지표, 근거 ID만 전달합니다.",
        columns: [
          {
            key: "KeywordDemandSnapshot.keyword",
            label: "키워드",
            description: "안건 후보와 시즌 키워드 판단에 쓰는 표준 키워드명입니다.",
            sample: "부처님오신날 선물카드",
          },
          {
            key: "monthlyPcSearches",
            label: "PC 검색수",
            description: "원천 PC 검색수를 숫자로 정규화한 값입니다.",
            sample: "420",
          },
          {
            key: "monthlyMobileSearches",
            label: "모바일 검색수",
            description: "원천 모바일 검색수를 숫자로 정규화한 값입니다.",
            sample: "1800",
          },
          {
            key: "competitionIndex",
            label: "경쟁 수준",
            description: "LOW, MEDIUM, HIGH, UNKNOWN 중 하나로 저장합니다.",
            sample: "MEDIUM",
          },
          {
            key: "cachedUntil",
            label: "캐시 만료일",
            description: "동일 키워드를 다시 불러오기 전까지 참고할 수 있는 날짜입니다.",
            sample: "2026-05-23",
          },
          {
            key: "providerSyncReportId",
            label: "연동 실행 ID",
            description: "어떤 읽기 전용 수집에서 만들어졌는지 추적하는 내부 ID입니다.",
            sample: "provider-sync-search-ad-2026-05-22",
          },
          {
            key: "SearchAdKeywordInventorySnapshot.keyword",
            label: "광고 키워드 목록",
            description: "성과가 없어도 광고 API에서 읽은 키워드 목록을 브랜드별로 저장합니다.",
            sample: "기업 감사장",
          },
          {
            key: "SearchAdKeywordInventorySnapshot.campaignName/adGroupName",
            label: "캠페인/광고그룹",
            description: "키워드가 어느 광고 구조에 속하는지 저장해 브랜드와 실행 범위를 나눕니다.",
            sample: "커피프린트 파워링크 / 40_기타 감사장",
          },
          {
            key: "SearchAdKeywordInventorySnapshot.effectiveStatus",
            label: "실제 노출 상태",
            description: "캠페인, 광고그룹, 키워드 상태와 잠금을 합쳐 ON/OFF로 저장합니다.",
            sample: "ON",
          },
          {
            key: "SearchAdPerformanceSnapshot.keyword",
            label: "성과 키워드",
            description: "규칙 엔진이 저성과 여부를 판단한 광고 키워드입니다.",
            sample: "생일 답례품",
          },
          {
            key: "SearchAdPerformanceSnapshot.device",
            label: "기기",
            description: "PC, MOBILE, ALL 중 하나로 저장하는 집계 기기 조건입니다.",
            sample: "MOBILE",
          },
          {
            key: "SearchAdPerformanceSnapshot.timeSlot",
            label: "시간대",
            description: "시간대 breakdown이 있을 때 저장하는 집계 구간입니다.",
            sample: "18-23",
          },
          {
            key: "SearchAdPerformanceSnapshot.clicks/conversions/cost/revenue",
            label: "성과 집계",
            description: "클릭, 전환, 광고비, 전환매출 집계입니다. 원문 행이 아니라 요약 스냅샷만 저장합니다.",
            sample: "클릭 64 / 주문 0 / 비용 38,400원",
          },
          {
            key: "SearchAdPerformanceSnapshot.trackingVerified",
            label: "추적 확인",
            description: "전환 추적/주문 연결이 확인됐는지 표시합니다. false면 데이가 먼저 확인합니다.",
            sample: "true",
          },
          {
            key: "ShoppingSearchAdPerformanceSnapshot.searchKeyword",
            label: "쇼핑 검색어",
            description: "쇼핑검색광고에서 실제 클릭이 발생한 검색어입니다.",
            sample: "스승의날 카드",
          },
          {
            key: "ShoppingSearchAdPerformanceSnapshot.productGroupName",
            label: "상품 그룹",
            description: "쇼핑검색광고 광고그룹과 연결된 상품 그룹명입니다.",
            sample: "스티커씨 선물카드 상품그룹",
          },
          {
            key: "ShoppingSearchAdPerformanceSnapshot.productImageUrl",
            label: "상품 이미지",
            description: "상품 그룹 또는 주문 이미지에서 확인된 대표 이미지 URL입니다. 없으면 화면에서 자동 대체 이미지를 씁니다.",
            sample: "https://cdn.example.test/products/gift-card-shopping.jpg",
          },
          {
            key: "ShoppingSearchAdPerformanceSnapshot.clicks/directConversionRate/cost",
            label: "쇼핑 성과",
            description: "최근 30일 클릭, 직접 전환율, 광고비 요약입니다. 원문 검색어 전체가 아니라 집계 스냅샷만 저장합니다.",
            sample: "클릭 42 / 직접전환율 0% / 비용 18,900원",
          },
        ],
        sampleRows: [
          {
            id: "search-ad-stored-sample-1",
            values: [
              { key: "keyword", label: "키워드", value: "부처님오신날 선물카드" },
              { key: "searches", label: "검색수", value: "PC 420 / 모바일 1,800" },
              { key: "competition", label: "경쟁", value: "MEDIUM" },
              { key: "rateLimit", label: "상태", value: "OK" },
            ],
          },
          {
            id: "search-ad-stored-sample-2",
            values: [
              { key: "keyword", label: "목록 키워드", value: "기업 감사장" },
              { key: "brand", label: "브랜드", value: "커피프린트" },
              { key: "scope", label: "광고 구조", value: "커피프린트 파워링크 / 40_기타 감사장" },
              { key: "status", label: "노출 상태", value: "ON" },
            ],
          },
          {
            id: "search-ad-stored-sample-3",
            values: [
              { key: "keyword", label: "성과 키워드", value: "생일 답례품" },
              { key: "device", label: "기기/시간", value: "모바일 18-23" },
              { key: "performance", label: "성과", value: "클릭 64 / 주문 0 / 비용 38,400원" },
              { key: "owner", label: "담당", value: "그로 조정안 또는 데이 추적 확인" },
            ],
          },
          {
            id: "search-ad-stored-sample-4",
            values: [
              { key: "searchKeyword", label: "쇼핑 검색어", value: "스승의날 카드" },
              { key: "productGroup", label: "상품 그룹", value: "스티커씨 선물카드" },
              { key: "performance", label: "쇼핑 성과", value: "클릭 42 / 직접전환율 0% / 비용 18,900원" },
              { key: "owner", label: "담당", value: "그로 상품 노출/입찰 점검" },
            ],
          },
        ],
      },
    },
    {
      providerKey: "datalab",
      providerLabel: "네이버 데이터랩",
      channelKey: "datalab",
      channelLabel: "마케팅 데이터",
      sourceUrl: "https://openapi.naver.com/v1/datalab/search",
      incoming: {
        id: "datalab-incoming",
        title: "불러오는 데이터",
        description: "검색어 트렌드 응답에서 기간별 상대 비율만 읽습니다.",
        safetyNote: "DataLab ratio는 절대 검색량이 아니므로 매출·검색수처럼 해석하지 않습니다.",
        columns: [
          {
            key: "startDate",
            label: "조회 시작일",
            description: "검색 트렌드를 요청한 시작 날짜입니다.",
            sample: "2026-04-22",
          },
          {
            key: "endDate",
            label: "조회 종료일",
            description: "검색 트렌드를 요청한 종료 날짜입니다.",
            sample: "2026-05-22",
          },
          {
            key: "timeUnit",
            label: "기간 단위",
            description: "date, week, month 중 하나입니다. 현재 운영 화면은 일 단위를 기본으로 봅니다.",
            sample: "date",
          },
          {
            key: "results.title",
            label: "키워드 묶음",
            description: "대표가 보는 검색어 그룹 이름입니다.",
            sample: "부처님오신날",
          },
          {
            key: "results.data.period",
            label: "구간",
            description: "상대 비율이 기록된 날짜 또는 기간입니다.",
            sample: "2026-05-01",
          },
          {
            key: "results.data.ratio",
            label: "상대 비율",
            description: "조회 구간의 최대값을 100으로 둔 상대 지표입니다.",
            sample: "100",
          },
        ],
        sampleRows: [
          {
            id: "datalab-incoming-sample-1",
            values: [
              { key: "title", label: "묶음", value: "부처님오신날" },
              { key: "period", label: "구간", value: "2026-05-01" },
              { key: "ratio", label: "비율", value: "100" },
              { key: "timeUnit", label: "단위", value: "date" },
            ],
          },
        ],
        sourceFieldGroups: [
          {
            id: "datalab-source-request",
            title: "요청 조건 원문",
            description: "데이터랩 트렌드 조회를 만들 때 사용한 요청 조건입니다. 성별/연령/기기 필터는 필요 시 세그먼트 분석 후보로 점검합니다.",
            fields: [
              { key: "startDate", label: "시작일", handling: "분석 기간으로 저장" },
              { key: "endDate", label: "종료일", handling: "분석 기간으로 저장" },
              { key: "timeUnit", label: "기간 단위", handling: "추이 단위로 저장" },
              { key: "keywordGroups[0].groupName", label: "키워드 그룹명", handling: "요청 조건 확인" },
              { key: "keywordGroups[0].keywords", label: "검색어 목록", handling: "요청 조건 확인, 원문 목록은 기본 저장 안 함" },
              { key: "device", label: "기기", handling: "PC/모바일 세그먼트 필요 시 점검" },
              { key: "ages", label: "연령대", handling: "연령 세그먼트 필요 시 점검" },
              { key: "gender", label: "성별", handling: "성별 세그먼트 필요 시 점검" },
            ],
          },
          {
            id: "datalab-source-search-result",
            title: "검색 트렌드 응답",
            description: "데이터랩 검색 트렌드 응답 원문 필드입니다.",
            fields: [
              { key: "startDate", label: "시작일", handling: "분석 기간으로 저장" },
              { key: "endDate", label: "종료일", handling: "분석 기간으로 저장" },
              { key: "timeUnit", label: "기간 단위", handling: "추이 단위로 저장" },
              { key: "results[0].title", label: "묶음", handling: "키워드 묶음 이름으로 저장" },
              { key: "results[0].keywords", label: "검색어", handling: "요청 조건 확인용, 원문 목록은 저장 안 함" },
              { key: "results[0].data[0].period", label: "구간", handling: "기간별 추이 구간으로 저장" },
              { key: "results[0].data[0].ratio", label: "상대 비율", handling: "절대 검색량이 아닌 상대값으로 저장" },
            ],
          },
        ],
      },
      stored: {
        id: "datalab-stored",
        title: "저장하는 데이터",
        description: "상대 비율 시계열을 검색 추이 요약으로 저장하고, 안건 판단에는 상승·하락 흐름만 사용합니다.",
        safetyNote: "AI에는 전체 원천 응답 대신 대표 구간과 요약만 넘깁니다.",
        columns: [
          {
            key: "SearchTrendSnapshot.keywordGroupName",
            label: "키워드 묶음",
            description: "검색 추이 요약의 대표 그룹명입니다.",
            sample: "부처님오신날",
          },
          {
            key: "timeUnit",
            label: "기간 단위",
            description: "저장된 추이의 단위입니다.",
            sample: "date",
          },
          {
            key: "startDate/endDate",
            label: "분석 기간",
            description: "추이를 비교할 시작일과 종료일입니다.",
            sample: "2026-04-22 ~ 2026-05-22",
          },
          {
            key: "ratios",
            label: "상대 비율 목록",
            description: "기간별 ratio만 저장합니다.",
            sample: "2026-05-01: 100",
          },
          {
            key: "note",
            label: "해석 주석",
            description: "절대 검색량이 아니라는 내부 주석입니다.",
            sample: "relative_ratio_not_absolute_volume",
          },
        ],
        sampleRows: [
          {
            id: "datalab-stored-sample-1",
            values: [
              { key: "keywordGroupName", label: "묶음", value: "부처님오신날" },
              { key: "window", label: "기간", value: "2026-04-22 ~ 2026-05-22" },
              { key: "ratios", label: "대표 비율", value: "2026-05-01: 100" },
              { key: "note", label: "주석", value: "상대값" },
            ],
          },
        ],
      },
    },
    {
      providerKey: "smartstore",
      providerLabel: "스마트스토어(스티커씨)",
      channelKey: "smartstore-stickersee",
      channelLabel: "스마트스토어(스티커씨)",
      brandLabel: "스티커씨",
      sourceUrl: "https://api.commerce.naver.com/external/v1/pay-order/seller/product-orders/query",
      incoming: {
        id: "smartstore-incoming",
        title: "불러오는 데이터",
        description: "토큰 발급 후 최근 변경 주문 ID를 가져오고, 주문 상세의 상품명/결제 금액과 원상품 조회의 대표 이미지만 집계합니다.",
        safetyNote: "토큰, 시크릿, 주문번호 목록, 원상품 번호, 주문/상품 원문 행은 저장하지 않습니다.",
        columns: [
          {
            key: "lastChangedFrom/lastChangedTo",
            label: "변경 조회 기간",
            description: "최근 변경 주문을 찾는 시작/종료 시각입니다.",
            sample: "2026-05-21T00:00:00Z ~ 2026-05-22T00:00:00Z",
          },
          {
            key: "productOrderId",
            label: "상품주문번호",
            description: "상세 조회에만 쓰는 주문 식별자입니다. 저장하지 않습니다.",
            sample: "po-1",
          },
          {
            key: "productOrder.productName",
            label: "상품명",
            description: "상품별 매출/주문 집계와 상위 상품 추출에 쓰는 이름입니다.",
            sample: "선물카드",
          },
          {
            key: "productOrder.originalProductId",
            label: "원상품 번호",
            description: "상위 상품 대표 이미지를 한 번 더 읽을 때만 쓰는 상품 식별자입니다.",
            sample: "조회 후 저장 안 함",
          },
          {
            key: "originProduct.images.representativeImage.url",
            label: "대표 이미지 URL",
            description: "상품 카드에 보여줄 상위 상품 대표 이미지입니다. 없거나 실패하면 화면 썸네일로 대체합니다.",
            sample: "https://example.test/products/gift-card.jpg",
          },
          {
            key: "productOrder.totalPaymentAmount",
            label: "결제 금액",
            description: "스티커씨 매출 집계에 합산하는 금액 후보입니다.",
            sample: "7,000",
          },
          {
            key: "access_token",
            label: "접근 토큰",
            description: "요청 인증에만 쓰고 저장하지 않는 값입니다.",
            sample: "저장 안 함",
          },
        ],
        sampleRows: [
          {
            id: "smartstore-incoming-sample-1",
            values: [
              { key: "productOrderId", label: "주문", value: "po-1" },
              { key: "productName", label: "상품", value: "선물카드" },
              { key: "originalProductId", label: "원상품", value: "조회 후 저장 안 함" },
              { key: "representativeImage", label: "이미지", value: "대표 이미지 URL" },
              { key: "totalPaymentAmount", label: "금액", value: "7,000원" },
              { key: "token", label: "토큰", value: "저장 안 함" },
            ],
          },
        ],
        sourceFieldGroups: [
          {
            id: "smartstore-source-token",
            title: "토큰 응답",
            description: "네이버 커머스 인증 응답 원문 필드입니다. 인증 값은 요청에만 쓰고 저장하지 않습니다.",
            fields: [
              { key: "access_token", label: "접근 토큰", handling: "요청 인증에만 사용, 저장 안 함" },
              { key: "accessToken", label: "접근 토큰 대체명", handling: "요청 인증에만 사용, 저장 안 함" },
              { key: "token_type", label: "토큰 타입", handling: "요청 헤더 구성에 사용, 저장 안 함" },
              { key: "tokenType", label: "토큰 타입 대체명", handling: "요청 헤더 구성에 사용, 저장 안 함" },
              { key: "expires_in", label: "만료 초", handling: "토큰 재발급 판단 후보, 저장 안 함" },
              { key: "expiresIn", label: "만료 초 대체명", handling: "토큰 재발급 판단 후보, 저장 안 함" },
              { key: "scope", label: "권한 범위", handling: "권한 점검 후보, 저장 안 함" },
            ],
          },
          {
            id: "smartstore-source-last-changed",
            title: "최근 변경 주문 응답",
            description: "변경 상품 주문 내역 조회 응답 원문 필드입니다. 상세 조회에 필요한 상품주문번호만 사용하고 원문 행은 저장하지 않습니다.",
            fields: [
              { key: "timestamp", label: "응답 시각", handling: "오류/응답 추적 후보, 기본 저장 안 함" },
              { key: "traceId", label: "추적 ID", handling: "오류/응답 추적 후보, 기본 저장 안 함" },
              { key: "data", label: "응답 데이터", handling: "응답 루트 후보" },
              { key: "lastChangeStatuses", label: "변경 목록", handling: "목록 루트 후보, 원문 저장 안 함" },
              { key: "lastChangedStatuses", label: "변경 목록 대체명", handling: "목록 루트 후보, 원문 저장 안 함" },
              { key: "data[]", label: "배열 응답", handling: "목록 루트 후보, 원문 저장 안 함" },
              { key: "data.lastChangeStatuses", label: "data 내부 변경 목록", handling: "목록 루트 후보, 원문 저장 안 함" },
              { key: "data.lastChangedStatuses", label: "data 내부 대체 목록", handling: "목록 루트 후보, 원문 저장 안 함" },
              { key: "data.more.moreFrom", label: "다음 조회 시작", handling: "페이징 후보, 기본 저장 안 함" },
              { key: "data.more.moreSequence", label: "다음 조회 순번", handling: "페이징 후보, 기본 저장 안 함" },
              { key: "lastChangeStatuses[0].orderId", label: "주문 ID", handling: "식별자 저장 안 함" },
              { key: "lastChangeStatuses[0].productOrderId", label: "상품주문번호", handling: "상세 조회에만 사용, 저장 안 함" },
              { key: "lastChangeStatuses[0].lastChangedType", label: "최종 변경 구분", handling: "상태 변화 점검 후보, 원문 저장 안 함" },
              { key: "lastChangeStatuses[0].paymentDate", label: "결제 일시", handling: "기간 검증 후보, 원문 저장 안 함" },
              { key: "lastChangeStatuses[0].lastChangedDate", label: "변경시각", handling: "조회 창 판단에 사용, 원문 저장 안 함" },
              { key: "lastChangeStatuses[0].productOrderStatus", label: "주문상태", handling: "필터 판단에 사용, 원문 저장 안 함" },
              { key: "lastChangeStatuses[0].claimType", label: "클레임 구분", handling: "취소/반품 영향 점검 후보, 원문 저장 안 함" },
              { key: "lastChangeStatuses[0].claimStatus", label: "클레임 상태", handling: "취소/반품 영향 점검 후보, 원문 저장 안 함" },
              { key: "lastChangeStatuses[0].receiverAddressChanged", label: "배송지 변경 여부", handling: "개인정보 변경 신호라 저장 안 함" },
              { key: "lastChangeStatuses[0].giftReceivingStatus", label: "선물 수락 상태", handling: "선물 주문 분석 후보, 원문 저장 안 함" },
              { key: "Authorization", label: "인증 토큰", handling: "요청에만 사용, 저장 안 함" },
            ],
          },
          {
            id: "smartstore-source-product-order",
            title: "주문 상세 응답",
            description: "상품 주문 상세 내역 조회 응답의 주요 원문 필드입니다. 주문 특성에 따라 하위 노드는 달라질 수 있어 개인정보/클레임/배송 필드는 저장하지 않고 점검 후보로만 둡니다.",
            fields: [
              { key: "timestamp", label: "응답 시각", handling: "오류/응답 추적 후보, 기본 저장 안 함" },
              { key: "traceId", label: "추적 ID", handling: "오류/응답 추적 후보, 기본 저장 안 함" },
              { key: "data", label: "응답 데이터", handling: "응답 루트 후보" },
              { key: "productOrders", label: "주문 상세 목록", handling: "상세 목록 루트 후보, 원문 저장 안 함" },
              { key: "contents", label: "상세 목록 대체명", handling: "상세 목록 루트 후보, 원문 저장 안 함" },
              { key: "data[]", label: "배열 응답", handling: "상세 목록 루트 후보, 원문 저장 안 함" },
              { key: "data.productOrders", label: "data 내부 상세 목록", handling: "상세 목록 루트 후보, 원문 저장 안 함" },
              { key: "data.contents", label: "data 내부 대체 목록", handling: "상세 목록 루트 후보, 원문 저장 안 함" },
              { key: "productOrders[0].productOrder.productOrderId", label: "상품주문번호", handling: "식별자 저장 안 함" },
              { key: "productOrders[0].productOrder.productName", label: "상품명", handling: "상위 상품 집계에 사용" },
              { key: "productOrders[0].productOrder.totalPaymentAmount", label: "결제 금액", handling: "매출 합산에 사용" },
              { key: "productOrders[0].productOrder.totalProductAmount", label: "상품 금액", handling: "결제 금액 후보, 원문 저장 안 함" },
              { key: "productOrders[0].productOrder.totalOrderAmount", label: "주문 금액", handling: "결제 금액 후보, 원문 저장 안 함" },
              { key: "productOrders[0].productOrder.paymentAmount", label: "결제 금액 대체", handling: "결제 금액 후보, 원문 저장 안 함" },
              { key: "productOrders[0].productOrder.productOrderAmount", label: "상품주문 금액", handling: "결제 금액 후보, 원문 저장 안 함" },
              { key: "productOrders[0].productOrder.quantity", label: "수량", handling: "주문 집계 확인용, 원문 저장 안 함" },
              { key: "productOrders[0].payment.totalPaymentAmount", label: "결제 객체 금액", handling: "결제 금액 후보, 원문 저장 안 함" },
              { key: "productOrders[0].order.generalPaymentAmount", label: "주문 객체 금액", handling: "결제 금액 후보, 원문 저장 안 함" },
              { key: "productOrders[0].order.orderId", label: "주문 ID", handling: "식별자 저장 안 함" },
              { key: "productOrders[0].shippingAddress", label: "배송지", handling: "개인정보로 저장 안 함" },
            ],
          },
          {
            id: "smartstore-source-origin-product",
            title: "원상품 조회 응답",
            description: "주문 상세의 원상품 번호로 대표 이미지를 확인하는 읽기 전용 상품 응답입니다. 원상품 번호와 상품 원문은 저장하지 않고 대표 이미지 URL만 집계 스냅샷에 반영합니다.",
            fields: [
              { key: "originProduct.statusType", label: "판매 상태", handling: "상품 상태 점검 후보, 기본 저장 안 함" },
              { key: "originProduct.name", label: "원상품명", handling: "상품명 교차 검증 후보, 기본 저장 안 함" },
              { key: "originProduct.images", label: "상품 이미지 묶음", handling: "대표 이미지 확인용, 원문 저장 안 함" },
              { key: "originProduct.images.representativeImage.url", label: "대표 이미지 URL", handling: "상위 상품 카드 대표 이미지로 저장" },
              { key: "originProduct.images.optionalImages[0].url", label: "추가 이미지 URL", handling: "현재 MVP 저장 안 함" },
              { key: "originProduct.salePrice", label: "판매가", handling: "가격 점검 후보, 기본 저장 안 함" },
              { key: "originProduct.stockQuantity", label: "재고 수량", handling: "재고/품절 가설 후보, 기본 저장 안 함" },
            ],
          },
          {
            id: "smartstore-source-order",
            title: "주문 객체",
            description: "주문 금액과 주문자 관련 원문 필드입니다. 주문자 정보는 개인정보로 저장하지 않습니다.",
            fields: [
              { key: "productOrders[0].order.chargeAmountPaymentAmount", label: "충전금 결제액", handling: "결제 구성 점검 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.checkoutAccumulationPaymentAmount", label: "적립금 결제액", handling: "결제 구성 점검 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.generalPaymentAmount", label: "일반 결제액", handling: "매출 금액 후보" },
              { key: "productOrders[0].order.naverMileagePaymentAmount", label: "포인트 결제액", handling: "결제 구성 점검 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.orderDate", label: "주문 일시", handling: "주문 기간 점검 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.orderDiscountAmount", label: "주문 할인액", handling: "마진 분석 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.orderId", label: "주문 번호", handling: "식별자 저장 안 함" },
              { key: "productOrders[0].order.ordererId", label: "주문자 ID", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].order.ordererName", label: "주문자명", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].order.ordererTel", label: "주문자 연락처", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].order.paymentDate", label: "결제 일시", handling: "기간 검증 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.paymentDueDate", label: "결제 기한", handling: "결제 대기 분석 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.paymentMeans", label: "결제 수단", handling: "결제 구성 점검 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.payLocationType", label: "결제 위치", handling: "채널 분석 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.ordererNo", label: "주문자 번호", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].order.payLaterPaymentAmount", label: "후불 결제액", handling: "결제 구성 점검 후보, 기본 저장 안 함" },
              { key: "productOrders[0].order.isMembershipSubscribed", label: "멤버십 여부", handling: "회원 세그먼트 후보, 개인 식별 없이 집계만 검토" },
            ],
          },
          {
            id: "smartstore-source-product-order-detail",
            title: "상품주문 객체",
            description: "상품/옵션/배송/클레임 상태 원문 필드입니다. 상품명과 금액 외에는 필요성 검토 후 집계로만 다룹니다.",
            fields: [
              { key: "productOrders[0].productOrder.claimStatus", label: "클레임 상태", handling: "취소/반품 영향 점검 후보" },
              { key: "productOrders[0].productOrder.claimType", label: "클레임 구분", handling: "취소/반품 영향 점검 후보" },
              { key: "productOrders[0].productOrder.decisionDate", label: "구매 확정일", handling: "확정 매출 기준 후보" },
              { key: "productOrders[0].productOrder.delayedDispatchDetailedReason", label: "발송 지연 상세 사유", handling: "운영 이슈 점검 후보, 기본 저장 안 함" },
              { key: "productOrders[0].productOrder.delayedDispatchReason", label: "발송 지연 사유", handling: "운영 이슈 점검 후보, 기본 저장 안 함" },
              { key: "productOrders[0].productOrder.deliveryDiscountAmount", label: "배송비 할인액", handling: "마진 분석 후보" },
              { key: "productOrders[0].productOrder.deliveryFeeAmount", label: "배송비", handling: "마진 분석 후보" },
              { key: "productOrders[0].productOrder.deliveryPolicyType", label: "배송비 정책", handling: "마진/배송 정책 점검 후보" },
              { key: "productOrders[0].productOrder.expectedDeliveryMethod", label: "배송 방법", handling: "배송 방식 점검 후보" },
              { key: "productOrders[0].productOrder.freeGift", label: "사은품", handling: "프로모션 점검 후보" },
              { key: "productOrders[0].productOrder.mallId", label: "가맹점 ID", handling: "식별자 저장 안 함" },
              { key: "productOrders[0].productOrder.optionCode", label: "옵션 코드", handling: "옵션 분석 후보, 기본 저장 안 함" },
              { key: "productOrders[0].productOrder.optionPrice", label: "옵션 금액", handling: "상품/옵션 매출 후보" },
              { key: "productOrders[0].productOrder.packageNumber", label: "묶음배송 번호", handling: "식별자 저장 안 함" },
              { key: "productOrders[0].productOrder.placeOrderDate", label: "발주 확인일", handling: "운영 리드타임 후보" },
              { key: "productOrders[0].productOrder.placeOrderStatus", label: "발주 상태", handling: "운영 상태 후보" },
              { key: "productOrders[0].productOrder.productClass", label: "상품 종류", handling: "상품 분류 후보" },
              { key: "productOrders[0].productOrder.productDiscountAmount", label: "상품 할인액", handling: "마진 분석 후보" },
              { key: "productOrders[0].productOrder.initialProductDiscountAmount", label: "최초 상품 할인액", handling: "마진 분석 후보" },
              { key: "productOrders[0].productOrder.remainProductDiscountAmount", label: "잔여 상품 할인액", handling: "마진 분석 후보" },
              { key: "productOrders[0].productOrder.groupProductId", label: "그룹 상품 번호", handling: "상품 식별 후보, 기본 저장 안 함" },
              { key: "productOrders[0].productOrder.productId", label: "채널 상품 번호", handling: "상품 매핑 후보, 기본 저장 안 함" },
              { key: "productOrders[0].productOrder.originalProductId", label: "원상품 번호", handling: "상품 매핑 후보, 기본 저장 안 함" },
              { key: "productOrders[0].productOrder.merchantChannelId", label: "채널 번호", handling: "채널 매핑 후보, 기본 저장 안 함" },
              { key: "productOrders[0].productOrder.productOption", label: "상품 옵션", handling: "옵션별 기회 분석 후보" },
              { key: "productOrders[0].productOrder.productOrderStatus", label: "상품주문 상태", handling: "상태 필터 후보" },
              { key: "productOrders[0].productOrder.initialQuantity", label: "최초 수량", handling: "수량 집계 후보" },
              { key: "productOrders[0].productOrder.remainQuantity", label: "잔여 수량", handling: "취소/반품 영향 점검 후보" },
              { key: "productOrders[0].productOrder.sectionDeliveryFee", label: "지역별 추가 배송비", handling: "배송비 분석 후보" },
              { key: "productOrders[0].productOrder.sellerProductCode", label: "판매자 상품 코드", handling: "상품 매핑 후보" },
              { key: "productOrders[0].productOrder.shippingDueDate", label: "발송 기한", handling: "운영 리드타임 후보" },
            ],
          },
          {
            id: "smartstore-source-shipping",
            title: "배송지/수령 정보",
            description: "배송지와 수령 위치 원문 필드입니다. 개인정보가 포함될 수 있어 저장하지 않고 필요성만 점검합니다.",
            fields: [
              { key: "productOrders[0].shippingAddress.addressType", label: "주소 타입", handling: "배송 지역 구분 후보, 원문 저장 안 함" },
              { key: "productOrders[0].shippingAddress.baseAddress", label: "기본 주소", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].shippingAddress.city", label: "도시", handling: "지역 집계 후보, 원문 저장 안 함" },
              { key: "productOrders[0].shippingAddress.country", label: "국가", handling: "국내/해외 집계 후보" },
              { key: "productOrders[0].shippingAddress.detailedAddress", label: "상세 주소", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].shippingAddress.name", label: "수령인명", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].shippingAddress.state", label: "주/도", handling: "지역 집계 후보, 원문 저장 안 함" },
              { key: "productOrders[0].shippingAddress.tel1", label: "연락처 1", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].shippingAddress.tel2", label: "연락처 2", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].shippingAddress.zipCode", label: "우편번호", handling: "지역 집계 후보, 원문 저장 안 함" },
              { key: "productOrders[0].shippingAddress.isRoadNameAddress", label: "도로명 주소 여부", handling: "주소 유형 후보, 원문 저장 안 함" },
              { key: "productOrders[0].shippingAddress.pickupLocationType", label: "수령 위치 타입", handling: "배송 이슈 점검 후보, 원문 저장 안 함" },
              { key: "productOrders[0].shippingAddress.pickupLocationContent", label: "수령 위치 내용", handling: "개인정보/배송 메모로 저장 안 함" },
              { key: "productOrders[0].shippingAddress.entryMethod", label: "출입 방법", handling: "개인정보/배송 메모로 저장 안 함" },
            ],
          },
          {
            id: "smartstore-source-fulfillment-extra",
            title: "물류/옵션/프로모션 추가 노드",
            description: "주문 특성에 따라 제공되는 추가 하위 노드입니다. 상품/옵션/프로모션 분석 후보로만 점검합니다.",
            fields: [
              { key: "productOrders[0].productOrder.logisticsCompanyId", label: "물류사 코드", handling: "배송 분석 후보" },
              { key: "productOrders[0].productOrder.logisticsCenterId", label: "물류센터 코드", handling: "물류 분석 후보" },
              { key: "productOrders[0].productOrder.skuMappings[0].nsId", label: "네이버 SKU ID", handling: "SKU 매핑 후보" },
              { key: "productOrders[0].productOrder.skuMappings[0].nsBarcode", label: "SKU 바코드", handling: "식별자 저장 안 함" },
              { key: "productOrders[0].productOrder.skuMappings[0].pickingQuantityPerOrder", label: "피킹 수량", handling: "물류 수량 후보" },
              { key: "productOrders[0].productOrder.hopeDelivery.region", label: "희망 배송 지역", handling: "배송 수요 후보, 원문 저장 안 함" },
              { key: "productOrders[0].productOrder.hopeDelivery.additionalFee", label: "희망 배송 추가비", handling: "배송비 분석 후보" },
              { key: "productOrders[0].productOrder.hopeDelivery.hopeDeliveryYmd", label: "희망 배송일", handling: "시즌 배송 수요 후보" },
              { key: "productOrders[0].productOrder.hopeDelivery.hopeDeliveryHm", label: "희망 배송 시간", handling: "시간대 분석 후보, 기본 저장 안 함" },
              { key: "productOrders[0].productOrder.standardPurchaseOptions[0].optionId", label: "옵션 ID", handling: "옵션 매핑 후보" },
              { key: "productOrders[0].productOrder.standardPurchaseOptions[0].optionName", label: "옵션명", handling: "옵션 분석 후보" },
              { key: "productOrders[0].productOrder.standardPurchaseOptions[0].valueName", label: "옵션값", handling: "옵션 분석 후보" },
              { key: "productOrders[0].productOrder.appliedCardPromotion.promotionName", label: "카드 프로모션명", handling: "프로모션 분석 후보" },
              { key: "productOrders[0].productOrder.appliedCardPromotion.cardCompanyName", label: "카드사", handling: "프로모션 분석 후보" },
              { key: "productOrders[0].productOrder.appliedCardPromotion.promotionApplyAmount", label: "프로모션 금액", handling: "할인/마진 분석 후보" },
              { key: "productOrders[0].productOrder.appliedCardPromotion.brandCompanyBurdenRatio", label: "브랜드 부담률", handling: "마진 분석 후보" },
            ],
          },
          {
            id: "smartstore-source-claims",
            title: "클레임/반품/교환 노드",
            description: "취소, 반품, 교환 관련 하위 노드입니다. 성과 분석 때 취소/반품 영향을 보기 위한 후보이며 개인정보 주소는 저장하지 않습니다.",
            fields: [
              { key: "productOrders[0].currentClaim.claimType", label: "현재 클레임 구분", handling: "취소/반품 영향 후보" },
              { key: "productOrders[0].currentClaim.claimId", label: "현재 클레임 ID", handling: "식별자 저장 안 함" },
              { key: "productOrders[0].currentClaim.claimStatus", label: "현재 클레임 상태", handling: "취소/반품 영향 후보" },
              { key: "productOrders[0].currentClaim.claimRequestDate", label: "클레임 요청일", handling: "성과 제외/반영 시점 후보" },
              { key: "productOrders[0].completedClaims[0].claimType", label: "완료 클레임 구분", handling: "취소/반품 이력 후보" },
              { key: "productOrders[0].completedClaims[0].claimStatus", label: "완료 클레임 상태", handling: "취소/반품 이력 후보" },
              { key: "productOrders[0].completedClaims[0].requestChannel", label: "접수 채널", handling: "CS 채널 분석 후보" },
              { key: "productOrders[0].completedClaims[0].claimRequestReason", label: "클레임 사유", handling: "상품 개선 후보, 원문 저장 전 검토 필요" },
              { key: "productOrders[0].completedClaims[0].refundExpectedDate", label: "환불 예정일", handling: "정산 영향 후보" },
              { key: "productOrders[0].completedClaims[0].refundStandbyStatus", label: "환불 대기 상태", handling: "정산 영향 후보" },
              { key: "productOrders[0].completedClaims[0].requestQuantity", label: "요청 수량", handling: "반품/교환 수량 후보" },
              { key: "productOrders[0].completedClaims[0].claimDeliveryFeeDemandAmount", label: "클레임 배송비 청구액", handling: "마진 영향 후보" },
              { key: "productOrders[0].completedClaims[0].claimDeliveryFeePayMeans", label: "클레임 배송비 결제 수단", handling: "정산 영향 후보" },
              { key: "productOrders[0].completedClaims[0].claimDeliveryFeePayMethod", label: "클레임 배송비 결제 방법", handling: "정산 영향 후보" },
              { key: "productOrders[0].completedClaims[0].collectAddress", label: "수거지 주소", handling: "개인정보로 저장 안 함" },
              { key: "productOrders[0].completedClaims[0].returnReceiveAddress", label: "반품 수령 주소", handling: "개인정보로 저장 안 함" },
            ],
          },
        ],
      },
      stored: {
        id: "smartstore-stored",
        title: "저장하는 데이터",
        description: "스티커씨 운영 판단에 필요한 주문 수, 매출, 상위 상품, 대표 이미지만 집계 스냅샷으로 저장합니다.",
        safetyNote: "고객 정보, 주문 원문, 원상품 번호, 상품 원문은 DB에 남기지 않는 집계 전용 계약입니다.",
        columns: [
          {
            key: "CommerceAggregateSnapshot.brandKey",
            label: "브랜드",
            description: "스티커씨 스마트스토어를 구분하는 내부 키입니다.",
            sample: "STICKERSEE",
          },
          {
            key: "windowDays",
            label: "집계 기간",
            description: "며칠 치 주문을 묶었는지 나타냅니다.",
            sample: "30",
          },
          {
            key: "paidOrderCount",
            label: "결제 주문수",
            description: "조회 기간 안에서 확인된 결제 주문 건수입니다.",
            sample: "100",
          },
          {
            key: "grossSales",
            label: "매출 합계",
            description: "상품 주문 금액을 합산한 스티커씨 매출입니다.",
            sample: "600,120",
          },
          {
            key: "topProductName",
            label: "상위 상품",
            description: "집계된 주문에서 대표로 노출할 상품명입니다.",
            sample: "선물카드",
          },
          {
            key: "topProductImageUrl",
            label: "대표 이미지",
            description: "원상품 조회에서 확인한 대표 이미지 URL입니다. 값이 없으면 화면에서 상품명 기반 썸네일을 대신 만듭니다.",
            sample: "https://example.test/products/gift-card.jpg",
          },
          {
            key: "dataScope",
            label: "저장 범위",
            description: "원천 행이 아닌 집계만 저장한다는 표시입니다.",
            sample: "aggregate_only",
          },
        ],
        sampleRows: [
          {
            id: "smartstore-stored-sample-1",
            values: [
              { key: "brandKey", label: "브랜드", value: "STICKERSEE" },
              { key: "orders", label: "주문", value: "100건" },
              { key: "grossSales", label: "매출", value: "600,120원" },
              { key: "topProductName", label: "상위 상품", value: "선물카드" },
              { key: "topProductImageUrl", label: "대표 이미지", value: "상품 이미지 URL 또는 자동 썸네일" },
            ],
          },
        ],
      },
    },
    {
      providerKey: "shop",
      providerLabel: "쇼핑몰(커피프린트)",
      channelKey: "shop-coffeeprint",
      channelLabel: "쇼핑몰(커피프린트)",
      brandLabel: "커피프린트",
      sourceUrl: "integrations/youngcart-bridge/README.md",
      incoming: {
        id: "shop-incoming",
        title: "불러오는 데이터",
        description: "영카트 직접 DB가 아니라 토큰 보호 브리지에서 커피프린트 주문/재구매 집계만 읽습니다.",
        safetyNote: "연결 토큰, DB 정보, 고객/주문 원문 행은 저장하지 않습니다.",
        columns: [
          {
            key: "brandKey",
            label: "브랜드",
            description: "브리지가 반환하는 쇼핑몰 브랜드 키입니다.",
            sample: "COFFEEPRINT",
          },
          {
            key: "windowDays",
            label: "집계 기간",
            description: "브리지에서 집계한 기간입니다.",
            sample: "30",
          },
          {
            key: "orderCount",
            label: "주문수",
            description: "기간 내 주문 건수입니다.",
            sample: "28",
          },
          {
            key: "repeatCustomerCount",
            label: "재구매 고객수",
            description: "기간 내 반복 구매로 분류된 고객 수입니다.",
            sample: "4",
          },
          {
            key: "grossSales",
            label: "매출 합계",
            description: "기간 내 주문 금액 합계입니다.",
            sample: "880,000",
          },
          {
            key: "averageOrderValue",
            label: "평균 주문금액",
            description: "객단가 판단에 쓰는 평균 주문 금액입니다.",
            sample: "51,765",
          },
        ],
        sampleRows: [
          {
            id: "shop-incoming-sample-1",
            values: [
              { key: "brandKey", label: "브랜드", value: "COFFEEPRINT" },
              { key: "orderCount", label: "주문", value: "28건" },
              { key: "repeatCustomerCount", label: "재구매", value: "4명" },
              { key: "grossSales", label: "매출", value: "880,000원" },
            ],
          },
        ],
        sourceFieldGroups: [
          {
            id: "shop-source-bridge-aggregate",
            title: "bridge aggregate response",
            description: "영카트 브리지가 반환하는 원문 집계 응답 필드입니다. 고객/주문 원문 행은 브리지 밖으로 내보내지 않습니다.",
            fields: [
              { key: "status", label: "브리지 상태", handling: "브리지 응답 점검 후보" },
              { key: "message", label: "브리지 메시지", handling: "오류/응답 점검 후보, 기본 저장 안 함" },
              { key: "brandKey", label: "브랜드", handling: "쇼핑몰 브랜드 구분에 사용" },
              { key: "windowDays", label: "집계 기간", handling: "집계 기간으로 저장" },
              { key: "orderCount", label: "주문수", handling: "주문 집계로 저장" },
              { key: "repeatCustomerCount", label: "재구매 고객수", handling: "재구매 세그먼트 크기로 저장" },
              { key: "grossSales", label: "매출", handling: "매출 집계로 저장" },
              { key: "averageOrderValue", label: "평균 주문금액", handling: "객단가로 저장" },
              { key: "collectedAt", label: "수집 시각", handling: "수집 시각으로 저장" },
              { key: "dataScope", label: "데이터 범위", handling: "aggregate_only 확인 후보" },
              { key: "sourceVersion", label: "브리지 버전", handling: "브리지 계약 변경 점검 후보" },
            ],
          },
        ],
      },
      stored: {
        id: "shop-stored",
        title: "저장하는 데이터",
        description: "커피프린트 운영 판단에 필요한 주문, 재구매, 매출, 객단가만 집계 스냅샷으로 저장합니다.",
        safetyNote: "개인정보와 주문 원문은 저장하지 않고 세그먼트 크기만 남깁니다.",
        columns: [
          {
            key: "ShopAggregateSnapshot.brandKey",
            label: "브랜드",
            description: "커피프린트 쇼핑몰을 구분하는 내부 키입니다.",
            sample: "COFFEEPRINT",
          },
          {
            key: "windowDays",
            label: "집계 기간",
            description: "며칠 치 주문/재구매를 묶었는지 나타냅니다.",
            sample: "30",
          },
          {
            key: "orderCount",
            label: "주문수",
            description: "집계 기간의 주문 건수입니다.",
            sample: "28",
          },
          {
            key: "repeatCustomerCount",
            label: "재구매 고객수",
            description: "재구매 세그먼트 크기입니다.",
            sample: "4",
          },
          {
            key: "grossSales",
            label: "매출 합계",
            description: "커피프린트 쇼핑몰 매출 합계입니다.",
            sample: "880,000",
          },
          {
            key: "averageOrderValue",
            label: "평균 주문금액",
            description: "상품/CRM 안건의 객단가 기준입니다.",
            sample: "51,765",
          },
        ],
        sampleRows: [
          {
            id: "shop-stored-sample-1",
            values: [
              { key: "brandKey", label: "브랜드", value: "COFFEEPRINT" },
              { key: "orderCount", label: "주문", value: "28건" },
              { key: "repeatCustomerCount", label: "재구매", value: "4명" },
              { key: "averageOrderValue", label: "객단가", value: "51,765원" },
            ],
          },
        ],
      },
    },
  ];
}
