import { getProviderHistoryPolicy } from "@/lib/domain";
import { buildProviderDataContracts } from "./provider-data-contracts";
import type { AgendaRoomViewModel } from "./types";

export const agendaRoomSample: AgendaRoomViewModel = {
  generatedAt: "2026-05-22 09:20",
  moaReport: {
    title: "모아 종합 보고",
    summary: "대표 결재 대기 3건, 추가 근거 대기 2건으로 정리했습니다.",
    reportCount: 6,
  },
  summary: {
    waitingApproval: 3,
    waitingEvidence: 2,
    readyToApply: 2,
    failedExecutions: 1,
  },
  inboxBuckets: [
    {
      id: "TODAY_APPROVAL",
      label: "오늘 결재",
      description: "대표 판단을 기다리는 실행 가능 안건",
      count: 3,
      tone: "approval",
    },
    {
      id: "SEASONAL_KEYWORD_REVIEW",
      label: "시즌 키워드",
      description: "음력/양력 이벤트 기준 광고 운영안",
      count: 2,
      tone: "season",
    },
    {
      id: "TRACKING_OUTCOME",
      label: "성과 추적",
      description: "승인 후 확인할 체크포인트",
      count: 3,
      tone: "tracking",
    },
    {
      id: "WAITING_EVIDENCE",
      label: "근거 대기",
      description: "데이 또는 담당자가 보강할 안건",
      count: 2,
      tone: "evidence",
    },
    {
      id: "AUTO_HOLD",
      label: "자동 보류",
      description: "중복/근거 부족으로 올라오지 않은 후보",
      count: 0,
      tone: "hold",
    },
    {
      id: "FAILED_EXECUTION",
      label: "실패 실행",
      description: "부분 실패나 수동 처리가 필요한 작업",
      count: 1,
      tone: "failure",
    },
  ],
  characters: [
    {
      id: "moa",
      name: "모아",
      role: "업무실장",
      tone: "coordinator",
      status: "담당자 안건을 묶어 대표 승인 대기열로 정리 중",
      workload: 72,
      queueCount: 6,
    },
    {
      id: "gro",
      name: "그로",
      role: "성장 담당",
      tone: "growth",
      status: "네이버 키워드광고 비용 급등 후보 검토",
      workload: 66,
      queueCount: 3,
    },
    {
      id: "pro",
      name: "프로",
      role: "상품 담당",
      tone: "product",
      status: "시즌 상품 조합과 신규 상품 후보 발굴",
      workload: 54,
      queueCount: 2,
    },
    {
      id: "copy",
      name: "카피",
      role: "메시지 담당",
      tone: "copy",
      status: "부처님오신날 선물카드 문구 초안 작성",
      workload: 41,
      queueCount: 2,
    },
    {
      id: "ripi",
      name: "리피",
      role: "재구매 담당",
      tone: "crm",
      status: "구매 이력 기반 재구매 타이밍 추적",
      workload: 36,
      queueCount: 1,
    },
    {
      id: "maru",
      name: "마루",
      role: "손익 담당",
      tone: "finance",
      status: "승인 시 예산 한도와 마진 영향 점검",
      workload: 58,
      queueCount: 4,
    },
    {
      id: "day",
      name: "데이",
      role: "데이터 담당",
      tone: "data",
      status: "음력 명절 비교 기준 캘린더 정리",
      workload: 63,
      queueCount: 3,
    },
  ],
  agendaCards: [
    {
      id: "agenda-001",
      owner: "그로",
      status: "승인 대기",
      title: "부처님오신날 선물카드 키워드 묶음 증액",
      source: "네이버 키워드광고 + 스마트스토어 주문",
      signal: "최근 7일 전환율이 전월 같은 요일 대비 18% 높고, 음력 기준 D-21 구간에서 작년 검색량이 상승했습니다.",
      decision: "대표 승인 시 추천 키워드 6개를 낮은 일예산으로 시작하고, 48시간 뒤 성과를 다시 보고합니다.",
      expectedImpact: "시즌 선물 수요 선점, 광고비는 하루 3만원 상한",
      risk: "불교 행사 수요가 지역/문구에 민감해 문구 승인 전 확장 금지",
      applyScope: "키워드광고 캠페인 초안만 생성, 외부 반영은 승인 후 실행",
      evidenceCount: 8,
      createdAt: "오늘 08:40",
    },
    {
      id: "agenda-002",
      owner: "프로",
      status: "근거 보강",
      title: "스승의날 단체 선물카드 상품 묶음 후보",
      source: "자체 쇼핑몰 주문 + 상품별 객단가",
      signal: "작년 양력 D-14 구간에서 단체 구매 객단가가 일반 구매보다 높았습니다.",
      decision: "옵션명, 재고, 마진 근거가 더 쌓이면 상품 노출 변경안을 올립니다.",
      expectedImpact: "단체 주문 전환율 개선",
      risk: "재고 동기화가 확인되지 않아 즉시 노출 변경 불가",
      applyScope: "상품 발굴 후보로 보류",
      evidenceCount: 4,
      createdAt: "오늘 07:55",
    },
    {
      id: "agenda-003",
      owner: "마루",
      status: "실패 확인",
      title: "어버이날 키워드 증액안 사전 실행 차단",
      source: "승인 게이트 + 예산 규칙",
      signal: "제안 일예산이 캠페인 월 잔여 한도를 초과했습니다.",
      decision: "예산을 낮춘 수정안을 그로에게 되돌려 다시 올리도록 요청했습니다.",
      expectedImpact: "과소비 방지",
      risk: "수정 전에는 외부 반영 없음",
      applyScope: "실행 차단 기록만 남김",
      evidenceCount: 5,
      createdAt: "어제 18:10",
    },
  ],
  seasonalKeywordPlans: [
    {
      id: "season-001",
      eventName: "부처님오신날",
      calendarBasis: "음력",
      comparisonWindow: "음력 행사일 기준 D-28 ~ D+7, 전년도 같은 상대일 비교",
      keywords: ["부처님오신날 선물카드", "사찰 행사 선물", "법회 답례품"],
      proposal: "신규 키워드는 소액 탐색 캠페인으로 시작하고, 문구는 카피 검토 후 승인 대기열로 올립니다.",
      budgetGuardrail: "초기 일예산 3만원, CPC 급등 시 자동 보류",
      nextAction: "대표 승인 필요",
    },
    {
      id: "season-002",
      eventName: "추석",
      calendarBasis: "음력",
      comparisonWindow: "음력 8월 15일 기준 D-45 ~ D+10, 작년/재작년 상대일 비교",
      keywords: ["추석 선물카드", "명절 답례 선물", "기업 명절 선물"],
      proposal: "전년도 성과가 있던 키워드와 올해 신규 검색어를 분리해 테스트합니다.",
      budgetGuardrail: "작년 광고수익률 하위 30% 키워드는 증액 금지",
      nextAction: "데이터 보강 중",
    },
  ],
  approvalPreviews: [
    {
      id: "approval-agenda-001",
      title: "부처님오신날 선물카드 키워드 묶음 증액",
      statusLabel: "대표 승인 대기",
      confidenceLabel: "승인 가능",
      riskLabel: "중간",
      evidenceSummary: "음력 이벤트 윈도우와 키워드 수요 근거가 연결되어 있습니다. 근거 3개.",
      diffSummary: "부처님오신날 이벤트용 키워드 3개를 소액 테스트 캠페인 초안으로 생성합니다.",
      beforeItems: ["키워드 없음", "일예산 0원"],
      afterItems: ["키워드 부처님오신날 선물카드, 사찰 행사 선물, 법회 답례품", "일예산 30,000원", "입찰 상한 900원"],
      rollbackPlan: "캠페인 초안 삭제 또는 키워드 일괄 pause로 되돌립니다.",
      measurementLabels: ["D+1 2026-05-23", "D+3 2026-05-25", "D+7 2026-05-29"],
      executorLabel: "네이버 키워드광고 모의 실행기",
      writeGateLabel: "외부 반영 잠금 확인 필요",
      primaryActionLabel: "승인 후 바로 반영",
      secondaryActions: ["초안만 승인", "수정 요청", "추가 근거 요청", "보류", "반려"],
      provenance: {
        summaryLabel: "근거 3개 · 실행 이력 1개 · 연동 수집 1개",
        evidenceLabels: ["키워드 수요 2개", "데이터 시그널 1개"],
        agentRunLabels: ["모아 계획 · 성공 · 240토큰 추정"],
        providerEvidenceLabels: ["네이버 키워드광고 · 동기화 완료 · 키워드 수요 2건"],
        checkpointLabels: ["D+1 2026-05-23 · 클릭률, 전환단가, 광고수익률"],
        safetyLabels: ["데이터 승인 가능", "위험 중간", "외부 반영 잠금 확인 필요", "원천 행 제외"],
      },
    },
  ],
  ownerDecisionFlows: [
    {
      id: "decision-approval-agenda-001-approve-and-apply",
      title: "부처님오신날 선물카드 키워드 묶음 증액",
      decisionLabel: "승인 후 바로 반영",
      memo: "샘플 기준으로 소액 테스트를 승인하되 실제 외부 반영은 닫아둡니다.",
      preflightStatusLabel: "실행 전 점검 통과",
      preflightChecks: [
        {
          label: "결재 상태",
          status: "통과",
          message: "대표 결재 대기 상태입니다.",
        },
        {
          label: "외부 반영 잠금",
          status: "주의",
          message: "실제 외부 반영 잠금이 닫혀 있어 모의 실행 또는 수동 처리가 필요합니다.",
        },
      ],
      executionStateLabel: "수동 처리 필요",
      executionNote: "대표 승인은 기록됐지만 실제 외부 반영 잠금이 닫혀 외부 계정에는 쓰지 않았습니다.",
      outcomeStateLabel: "판단 보류",
      outcomeSummary: "성과 판단은 체크포인트 도래 후 진행합니다.",
      outcomeEvidenceLabels: [],
      followUpTasks: ["모아: 외부 반영 잠금 상태를 대표에게 보고하고 수동 반영 또는 잠금 해제 여부 확인"],
    },
  ],
  providerDataContracts: buildProviderDataContracts(),
  providerReadiness: [
    {
      id: "search_ad",
      label: "네이버 키워드광고",
      statusLabel: "읽기 준비",
      tone: "warning",
      canReadLabel: "읽기 가능",
      canWriteLabel: "쓰기 차단",
      readScope: "통계와 키워드 조회 준비",
      writeScope: "키워드/입찰/예산 변경은 외부 반영 잠금으로 차단",
      missingEnvKeys: [],
      notes: ["공식 인증 헤더와 서명 구조를 확인한 뒤 읽기 전용으로만 사용합니다."],
      sourceUrl: "https://github.com/naver/searchad-apidoc",
    },
  ],
  providerSyncEvidence: [
    {
      id: "provider-sync-sample",
      label: "네이버 키워드광고 읽기 전용 수집",
      providerKey: "search_ad",
      providerGroup: "ad",
      channelKey: "search-ad",
      channelLabel: "마케팅 데이터",
      providerLabel: "네이버 키워드광고",
      statusLabel: "동기화 완료",
      tone: "ready",
      checkedAt: "2026-05-22 11:00",
      endpointLabel: "https://api.searchad.naver.com/keywordstool",
      httpStatusLabel: "응답 200",
      readOnlyLabel: "읽기 전용",
      networkLabel: "실제 조회",
      writeLabel: "쓰기 시도 없음",
      evidenceCountLabel: "근거 3개",
      snapshotLabels: ["키워드 수요 2건", "시그널 시즌 키워드 수요"],
      missingEnvKeys: [],
      notes: ["원천 행 없이 키워드 수요 요약만 저장합니다."],
      sourceUrl: "https://github.com/naver/searchad-apidoc",
      historyPolicy: getProviderHistoryPolicy("search_ad"),
    },
  ],
  plannerPreview: {
    title: "모아 규칙 기반 계획 요약",
    modeLabel: "규칙 기반 대체",
    summary: "원천 행 없이 집계 요약과 근거 ID만 사용합니다.",
    selectedAgendaIds: ["approval-agenda-001"],
    evidenceIds: ["kw-demand-buddha-gift-card"],
    tokenEstimateLabel: "예상 240토큰",
    rawRowsLabel: "원천 행 제외",
    constraints: ["집계 요약만 사용", "외부 반영 불가"],
    audit: {
      runId: "planner-audit-sample",
      inputId: "planner-input-sample",
      resultId: "planner-result-sample",
      providerLabel: "연동 규칙 기반",
      modelLabel: "모델 규칙 기반 대체",
      tokenUsageLabel: "380토큰 추정",
      billingLabel: "과금 없음",
      sourceCountLabels: ["후보 3건", "선택 1건", "근거 1개", "연동 메모 1개"],
      evidenceTraceLabel: "kw-demand-buddha-gift-card",
    },
  },
  llmCostGovernance: {
    statusLabel: "실제 호출 차단",
    tone: "blocked",
    liveCallAllowed: false,
    providerLabel: "연동 Gemini",
    modelLabel: "모델 gemini-3.1-flash-lite",
    credentialLabel: "키 설정됨",
    modeLabel: "현재 규칙 기반 대체",
    estimatedRunCostLabel: "이번 예상 단가 미설정",
    dailySpentLabel: "오늘 누적 0원",
    dailyBudgetLabel: "일 예산 미설정",
    dailyRemainingLabel: "잔여 예산 계산 대기",
    monthlySpentLabel: "이번 달 누적 0원",
    monthlyBudgetLabel: "월 예산 미설정",
    monthlyRemainingLabel: "월 잔여 계산 대기",
    runBudgetLabel: "1회 예산 미설정",
    rateBasisLabel: "공식 USD 가격표는 참고로 표시하고, 실제 원화 계산은 환경 단가가 있을 때만 수행합니다.",
    officialPricingSourceLabel: "Google AI 공식 가격표 · 2026-05-22 확인",
    pricingFormulaLabel:
      "공식 USD 단가에 적용 환율을 반영해 AI_LLM_COST_PER_1K_INPUT_KRW와 AI_LLM_COST_PER_1K_OUTPUT_KRW를 정하면 실제 호출 비용 가드가 계산됩니다.",
    officialPricingRows: [
      {
        modelKey: "gemini-3.5-flash",
        modelLabel: "Gemini 3.5 Flash",
        roleLabel: "전략 / 검토 · 현재 호출 후보",
        tierLabel: "Google Gemini Standard 유료 티어",
        inputPriceLabel: "입력 $1.50 / 100만 토큰",
        outputPriceLabel: "출력 $9.00 / 100만 토큰",
        cachePriceLabel: "캐시 $0.15 / 100만 토큰",
        sourceLabel: "Google AI 공식 가격표 · 2026-05-22 확인",
        sourceUrl: "https://ai.google.dev/gemini-api/docs/pricing?hl=en",
        tone: "active",
        note: "출력 단가는 thinking token을 포함한 기준입니다.",
      },
      {
        modelKey: "gemini-3.1-flash-lite",
        modelLabel: "Gemini 3.1 Flash-Lite",
        roleLabel: "기본",
        tierLabel: "Google Gemini Standard 유료 티어",
        inputPriceLabel: "입력 $0.25 / 100만 토큰",
        outputPriceLabel: "출력 $1.50 / 100만 토큰",
        cachePriceLabel: "캐시 $0.025 / 100만 토큰",
        sourceLabel: "Google AI 공식 가격표 · 2026-05-22 확인",
        sourceUrl: "https://ai.google.dev/gemini-api/docs/pricing?hl=en",
        tone: "reference",
        note: "텍스트/이미지/비디오 입력 기준입니다. 오디오 입력은 별도 단가입니다.",
      },
    ],
    plannedTokenLabels: ["입력 240토큰", "출력 140토큰", "총 380토큰", "원천 행 제외"],
    decisionSummary: "비용 정책 또는 토큰 잠금이 닫혀 있어 모아는 규칙 기반 대체로만 종합합니다.",
    gateChecks: [
      {
        id: "provider-credential",
        label: "연동 키",
        statusLabel: "통과",
        tone: "ready",
        message: "AI 모델 연동과 키가 설정되어 있습니다.",
      },
      {
        id: "rate-policy",
        label: "단가 정책",
        statusLabel: "차단",
        tone: "blocked",
        message: "AI_LLM_COST_PER_1K_INPUT_KRW와 AI_LLM_COST_PER_1K_OUTPUT_KRW가 필요합니다.",
      },
      {
        id: "daily-budget",
        label: "일 예산",
        statusLabel: "차단",
        tone: "blocked",
        message: "AI_LLM_DAILY_BUDGET_KRW 설정 전까지 실제 호출을 열지 않습니다.",
      },
    ],
  },
  agentRunSummary: {
    totalRuns: 1,
    totalTokensLabel: "380토큰",
    estimatedCostLabel: "0원",
    statusCountLabels: ["성공 1건", "실패 0건", "건너뜀 0건"],
    recentRuns: [
      {
        id: "planner-audit-sample",
        runnerLabel: "모아 계획",
        statusLabel: "성공",
        modelLabel: "규칙 기반 / 규칙 기반 대체",
        tokenLabel: "380토큰 추정",
        costLabel: "0원",
        evidenceLabel: "근거 1개",
        finishedAt: "2026-05-22 11:00",
      },
    ],
  },
  productGrowthOpportunities: [
    {
      id: "product-growth-sample",
      owner: "그로",
      kindLabel: "키워드 확장",
      confidenceLabel: "승인 가능",
      title: "선물카드 상품 키워드 확장 후보",
      targetLabel: "선물카드",
      summary: "스마트스토어 집계와 키워드 수요를 묶어 내부 검색광고 초안을 만들 후보입니다.",
      keywords: ["부처님오신날 선물카드", "추석 선물카드"],
      evidenceLabels: ["키워드 후보 2개", "읽기 전용 집계"],
      nextAction: "그로가 검색광고 키워드 초안을 작성",
      guardrail: "광고 키워드 추가, 입찰, 예산 변경은 외부 반영 잠금 전까지 차단",
      sourceReportIds: ["provider-sync-sample"],
    },
  ],
  aiEvidenceBriefs: [
    {
      id: "ai-evidence-sample-search-ad",
      providerKey: "search_ad",
      channelLabel: "네이버 키워드광고",
      title: "네이버 키워드광고 AI 판독 근거",
      decisionLabel: "판단 가능",
      tone: "ready",
      summary: "상위 키워드 2개와 시즌 검색 수요를 요약 근거로 사용합니다.",
      allowedUseCases: ["키워드 확장 후보 선별", "시즌 검색 수요 우선순위 판단"],
      blockedUseCases: ["광고비/입찰가 즉시 변경", "원천 검색어 전체 재해석"],
      evidenceIds: ["kw-demand-buddha-gift-card"],
      sourceReportIds: ["provider-sync-sample"],
      checkedAt: "2026-05-22 11:00",
      rawDataPolicyLabel: "원천 행 제외, 요약 근거와 근거 ID만 사용",
    },
  ],
  executionResults: [
    {
      id: "exec-001",
      title: "부처님오신날 캠페인 초안 생성",
      state: "대기",
      note: "승인 전에는 외부 계정에 쓰지 않습니다.",
    },
    {
      id: "exec-002",
      title: "어버이날 예산 증액 실행",
      state: "차단됨",
      note: "마루 예산 규칙에 의해 대표 승인 전 단계에서 중단했습니다.",
    },
    {
      id: "exec-003",
      title: "스마트스토어 주문 요약 동기화",
      state: "실행됨",
      note: "읽기 전용 요약만 업무실에 반영했습니다.",
    },
  ],
  outcomeCheckpoints: [
    {
      id: "outcome-001",
      title: "승인 후 48시간 성과 보고",
      metric: "클릭률, 전환율, 광고비, 주문액, 마진",
      status: "준비",
    },
    {
      id: "outcome-002",
      title: "시즌 종료 후 전년도 비교",
      metric: "음력 상대일 기준 매출/검색량/광고 효율",
      status: "판단 예정",
    },
    {
      id: "outcome-003",
      title: "실패 실행 재발 방지",
      metric: "차단 사유, 수정안 제출 여부",
      status: "관찰 중",
    },
  ],
};
